@baseUrl = http://213.233.184.82:8060
@user = admin
@pass = admin

### Create session and extract session_id
POST {{baseUrl}}/create-session HTTP/1.1
Authorization: Basic {{user}}:{{pass}}

### Get bot info
POST https://api.telegram.org/bot8192444599:AAEUDe-3BT73dPVNS_LRw-oceXbFCYQZ8-I/getMe HTTP/1.1

###

### RAG API - Health Check
GET {{baseUrl}}/health HTTP/1.1


# @name session
POST {{baseUrl}}/create-session HTTP/1.1
Authorization: Basic {{user}}:{{pass}}

###

@session_id = 0a268b19-f3e5-41d0-9bde-ac9f1f2cc21d

### Send query using extracted session_id
POST {{baseUrl}}/query HTTP/1.1
Content-Type: application/json
Authorization: Basic {{user}}:{{pass}}

{
    "session_id": "{{session_id}}",
    "query": "استاد آرش امینی چه سمتی در دانشکده دارد ؟"
}
